# Generated by Django 3.1.3 on 2023-04-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_auto_20230415_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='lanzamientomanga',
        ),
        migrations.AddField(
            model_name='manga',
            name='preciomanga',
            field=models.IntegerField(default=0),
        ),
    ]
