# Generated by Django 3.1.3 on 2023-04-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0004_auto_20230423_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='editorialmanga',
            field=models.TextField(default=''),
        ),
    ]
